trigger:
- main
- feature/*

pool: AvneshPool

stages:
- stage: Terraformtodo
  displayName: Terraformtodo
  jobs:
  - job: terraforminit_plan
    displayName: Terraform Init & Plan
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
       provider: 'azurerm'
       command: 'init'
       workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
       backendServiceArm: 'Monolithic-serviceconnection01'
       backendAzureRmStorageAccountName: 'devstg3912'
       backendAzureRmContainerName: 'devcontainer3912'
       backendAzureRmKey: 'dev3912key.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        environmentServiceNameAzureRM: 'Monolithic-serviceconnection01'


- stage: scanning
  displayName: scanning
  jobs:
  - job: terraformscanning
    displayName: terraformscanning
    steps: 
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'

- stage: Apply
  displayName: Apply
  jobs:
  - job: terraformApply
    displayName: terraformApply
    steps: 
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
       provider: 'azurerm'
       command: 'init'
       workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
       backendServiceArm: 'Monolithic-serviceconnection01'
       backendAzureRmStorageAccountName: 'devstg3912'
       backendAzureRmContainerName: 'devcontainer3912'
       backendAzureRmKey: 'dev3912key.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        environmentServiceNameAzureRM: 'Monolithic-serviceconnection01'